// Priority scale: 0.0 - 1.0
const SITE_PRIORITY = {
  DOMAIN: 1.0,
  FEATURE: 0.9,
  FEATURE_ENCOUNTERS_CATEGORY: 0.8,
  FEATURE_ENCOUNTERS_CATEGORY_MAP: 0.7,
  FEATURE_ENCOUNTERS_CATEGORY_MAP_BOSS: 0.6,
  FEATURE_ENCOUNTERS_CATEGORY_MAP_BOSS_SKILLS: 0.5,
};

module.exports = SITE_PRIORITY;
