name: "Code quality assurance: @exile-watch / doryani"

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize

jobs:
  code-quality-assurance:
    runs-on: ubuntu-latest
    steps:
      - name: Code quality assurance
        uses: exile-watch/doryani/code-quality-assurance@main
        with:
          GH_ACTOR: ${{ github.actor }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}